import { NavItem, Product, Brand } from './types';

export const COMPANY_INFO = {
  name: "100% Prodotto Italiano",
  claim: "Fabricant et distributeur de produits laitiers et alimentaires italiens pour les professionnels.",
  siren: "FR 83 903 535 268",
  address: "Uffici e Sede legale - 74 Avenue des Bouleaux, 91170 Viry-Châtillon (France)",
  logisticsAddress: "Logistica - 23 Rue du Saule Trapu, Massy 91300",
  email: "100prodotticaseari@gmail.com",
  contacts: {
    rosario: {
      name: "Rosario Sorrentino",
      phone: "+33 7 83 15 27 72",
      country: "FR",
    },
    francesco: {
      name: "Francesco Ricciardi",
      phone: "+39 366 548 7092",
      country: "IT",
    },
  },
};

export const NAV_ITEMS: NavItem[] = [
  { label: 'Home', path: '/' },
  { label: 'Chi Siamo', path: '/chi-siamo' },
  { label: 'Prodotti', path: '/prodotti' },
  { label: 'Territorio', path: '/territorio' },
  { label: 'Qualità', path: '/qualita' },
  { label: 'Contatti', path: '/contatti' },
];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Mozzarella di Bufala Campana DOP',
    category: 'Latticini',
    description: 'La regina della tavola. Mozzarella fresca prodotta esclusivamente con latte di bufala intero fresco.',
    isDop: true,
    isIgp: false,
    image: '/images/mozzarella.webp',
  },
  {
    id: '2',
    name: 'Burrata Pugliese IGP',
    category: 'Latticini',
    description: 'Un sacchetto di pasta filata morbida che racchiude un cuore cremoso di stracciatella.',
    isDop: false,
    isIgp: true,
    image: '/images/Burrata_pugliese.webp',
  },
  {
    id: '3',
    name: 'Parmigiano Reggiano DOP',
    category: 'Formaggi Stagionati',
    description: 'Il re dei formaggi, stagionato. Gusto ricco e friabile.',
    isDop: true,
    isIgp: false,
    image: '/images/Parmigiano.webp',
  },
  {
    id: '4',
    name: 'Prosciutto di Parma',
    category: 'Salumi',
    description: 'Dolce e raffinato, stagionato con cura nelle colline di Parma.',
    isDop: true,
    isIgp: false,
    image: '/images/prosciutto.webp',
  },
  {
    id: '5',
    name: 'Julienne Pizza',
    category: 'Latticini',
    description: 'formaggio fresco a pasta filata, prodotto esclusivamente con latte vaccino intero, noto per la sua consistenza morbida, il colore bianco candido e il sapore delicato di latte',
    isDop: true,
    isIgp: false,
    image: '/images/julienne.webp',
  },
  {
    id: '6',
    name: 'Pecorino Romano DOP',
    category: 'Formaggi Stagionati',
    description: 'Gusto intenso e piccante, simbolo della tradizione romana.',
    isDop: true,
    isIgp: false,
    image: '/images/pecorino.webp',
  },
  {
    id: '10',
    name: 'Fioridilatte Agerola Pizza',
    category: 'Latticini',
    description: 'Formaggio fresco a pasta filata, pronto a essere utilizzato in pizza.',
    isDop: true,
    isIgp: false,
    image: '/images/fiordilatte-agerola.webp',
  }
  ,
  {
    id: '11',
    name: 'Grana Padano DOP',
    category: 'Formaggi Stagionati',
    description: 'Formaggio a pasta dura, cotta e a lenta maturazione, fragrante e saporito.',
    isDop: true,
    isIgp: false,
    image: '/images/granda_padano.jpg',
  },
  {
    id: '12',
    name: 'Gorgonzola DOP',
    category: 'Formaggi Stagionati',
    description: 'Formaggio erborinato a pasta cruda, dal sapore deciso e inconfondibile.',
    isDop: true,
    isIgp: false,
    image: '/images/gorgonzola_bassi.jpg',
  }
  ,{
    id: '13',
    name: 'Taleggio DOP',
    category: 'Formaggi Stagionati',
    description: 'Formaggio a pasta molle e crosta lavata, dal profumo aromatico e sapore dolce.',
    isDop: true,
    isIgp: false,
    image: '/images/taleggio_a.png',
  },
  {
    id: '14',
    name: 'Mascarpone Granarolo',
    category: 'Formaggi Stagionati',
    description: 'Formaggio fresco cremoso, ingrediente essenziale per il Tiramisù e dolci al cucchiaio.',
    isDop: false,
    isIgp: false,
    image: '/images/mascarpone.jpg',
  },
  {
    id: '15',
    name: 'Treccione di Bufala Campana DOP',
    category: 'Latticini',
    description: 'Treccia di mozzarella di bufala campana, succosa e ricca di latte.',
    isDop: true,
    isIgp: false,
    image: '/images/treccione.jpg',
  },
  {
    id: '16',
    name: 'Ricotta di Bufala Campana DOP',
    category: 'Latticini',
    description: 'Ricotta fresca prodotta con siero di latte di bufala, morbida e gustosa.',
    isDop: true,
    isIgp: false,
    image: '/images/ricottaA.jpg',
  },
  {
    id: '17',
    name: 'Stracciatella Pugliese IGP',
    category: 'Latticini',
    description: 'Il cuore morbido e cremoso della burrata, un\'esplosione di gusto.',
    isDop: false,
    isIgp: true,
    image: '/images/stracciatella.jpg',
  },
  {
    id: '18',
    name: 'Prosciutto crudo San Daniele',
    category: 'Salumi',
    description: 'Prosciutto crudo stagionato dolce e raffinato, eccellenza friulana.',
    isDop: false,
    isIgp: false,
    image: '/images/CrudoSanDan.jpg',
  }
  ,{
    id: '19',
    name: 'Prosciutto Cotto Trinità',
    category: 'Salumi',
    description: 'Prosciutto cotto di alta qualità, morbido e dal sapore delicato.',
    isDop: false,
    isIgp: false,
    image: '/images/Cotto-trinità.png',
  },
  {
    id: '20',
    name: 'Prosciutto Cotto Casa Modena',
    category: 'Salumi',
    description: 'Gusto classico e bilanciato, ideale per ogni occasione.',
    isDop: false,
    isIgp: false,
    image: '/images/Cotto-casamodena.png',
  },
  {
    id: '21',
    name: 'Mortadella Professional Casa Modena',
    category: 'Salumi',
    description: 'Mortadella profumata e gustosa, prodotta secondo tradizione.',
    isDop: false,
    isIgp: false,
    image: '/images/mortadella-casamodena.jpg',
  },
  {
    id: '22',
    name: 'Mortadella Vismara',
    category: 'Salumi',
    description: 'Mortadella dal sapore intenso e speziato, con pistacchi.',
    isDop: false,
    isIgp: false,
    image: '/images/mortadella-vismara.jpg',
  },
  {
    id: '23',
    name: 'Spianata Bombieri',
    category: 'Salumi',
    description: 'Salame schiacciato tipico, dal gusto deciso e leggermente piccante.',
    isDop: false,
    isIgp: false,
    image: '/images/spianata-piccante.png',
  },
  {
    id: '24',
    name: 'Salame piccante bastone Bombieri',
    category: 'Salumi',
    description: 'Salame dalla forma allungata, arricchito con peperoncino per un gusto vivace.',
    isDop: false,
    isIgp: false,
    image: '/images/salame-piccante.jpeg',
  },
  {
    id: '25',
    name: 'Salame piccante bastone Coati',
    category: 'Salumi',
    description: 'Salame piccante stagionato, perfetto per antipasti e pizze.',
    isDop: false,
    isIgp: false,
    image: '/images/Coati-bastone.jpg',
  },
  {
    id: '26',
    name: 'Speck Moser premium',
    category: 'Salumi',
    description: 'Speck dell\'Alto Adige, affumicato e stagionato all\'aria fresca di montagna.',
    isDop: false,
    isIgp: false,
    image: '/images/speckmoser.jpg',
  },
  {
    id: '27',
    name: 'Bresaola Galli',
    category: 'Salumi',
    description: 'Salume magro e nutriente, ottenuto da punta d\'anca di manzo.',
    isDop: false,
    isIgp: false,
    image: '/images/Brisaula.jpg',
  },
  {
    id: '28',
    name: 'Nduja di Spilinga',
    category: 'Salumi',
    description: 'Salume spalmabile piccante calabrese, ideale su bruschette e per insaporire sughi.',
    isDop: false,
    isIgp: false,
    image: '/images/Nduja.jpg',
  },
  {
    id: '29',
    name: 'Cotto alle erbe Fiorucci',
    category: 'Salumi',
    description: 'Prosciutto cotto aromatizzato con una selezione di erbe fini.',
    isDop: false,
    isIgp: false,
    image: '/images/cotto-fiorucci.jpg',
  },
];

export const CATEGORY_BRANDS: Record<string, Brand[]> = {
  'Salumi': [
    { name: 'Bombieri', logo: '/images/bombieri.PNG' },
    { name: 'Casa Walser', logo: '/images/bresaola.PNG' },
    { name: 'Casa Modena', logo: '/images/casamodena.JPG' },
    { name: 'San Dan', logo: '/images/sandan.JPG' },
    { name: 'Vismara', logo: '/images/vismara.PNG' },
    { name: 'Trinita', logo: '/images/trinita.PNG' },
    { name: 'Il salumiere', logo: '/images/il_salumiere.JPG' },
    { name: 'Coati', logo: '/images/coati.PNG' },
    { name: 'Fiorucci', logo: '/images/fiorucci.JPG' },
  ],
  'Farine': [
    { name: 'Mulino Caputo', logo: '/images/caputo.jpeg' },
    { name: 'Mulino Piantoni', logo: '/images/Molino.jpeg' },
    { name: 'Mulino vigevano', logo: '/images/Molino vigevano.jpeg' },
    { name: 'Mulino Petra', logo: '/images/petra.jpeg' }
  ],
  'Pasta': [
    { name: 'De Cecco', logo: '/images/DeCecco.png' },
    { name: 'Divella', logo: '/images/Divella.jpeg' },
    { name: 'La Molisana', logo: '/images/la-molisana.png' },
    { name: 'Rummo', logo: '/images/rummo.jpg' },
    { name: 'Oro Giallo', logo: '/images/orogiallo.png' },
    { name: 'Riso Gallo', logo: '/images/risogallo.png' },
    { name: 'Casereccia', logo: '/images/logo_casereccia.png' },
    { name: 'MakeFood Italy', logo: '/images/makefood-logo.svg' }
  ],

  'Conserve': [
    { name: 'Solania', logo: '/images/solania.png' },
    { name: 'Pomorosso', logo: '/images/pomorosso.jpg' },
    { name: 'O Sol e Napoli', logo: '/images/osol.png' },
    { name: 'La Fiammante', logo: '/images/lafiammante.png' },
    { name: 'La Carmela', logo: '/images/lacarmela.jpg' },
    { name: 'La Rosina', logo: '/images/larosina.jpg' },
  ]

};
